.TH METEOGRAPH "1" "December 2001" "Meteo station tools" Othello
.SH NAME
meteograph \- draw graphs of meteo data
.SH SYNOPSIS
meteograph [
.B \-a
] [
.B \-c
] [
.B \-t
] [
.B \-d
] [
.BI \-e endtime
]
.BI \-f conffile
[
.BI \-g graphname
|
.BI \-G graphname
]
.IR interval ...
.SH DESCRIPTION
The 
.BR meteograph (1)
program computes graphs of meteo data for a weather station for various
sampling
.IR interval s.
Allowed values for the
.I interval
are 300, 1800, 7200 and 86400, resulting in graphs spanning a day,
a week, a month and a full year, respectively.
By default, the graph ends at the current point in time, but this
behaviour can be modified by specifying an end timestamp with
the 
.B \-e
option in the format
.IR YYYYMMDDhhmmss .

By default, all graphs are produced, i.e. for temperature, inside
temperature, barometric pressure, wind, rain and radiation.
The
.B \-g
and
.B \-G
options allow to modify the list of graphs to be produced.
The graphs are stored in files in the current working directory
unless a different directory is specified with the 
.B \-c
option. The file names are of the
form

.ce
.IR station - graphname - suffix .png

The
.I station
name is specified in the configuration file.
The suffix is one of
.IR day ,
.IR week ,
.I month
or
.IR year ,
for sampling intervals 300, 1800, 7200 and 86400 respectively.
The possible  graph names are summarized in the following  table

.TS
tab(&);
l l.
temperature&outside temperature
temperature_inside&inside temperature
barometer&barometric pressure
wind&wind speed and direction
rain&rain total
radiation&solar and uv radiation
.TE

The parameters defining these graphs are set in the
.BR meteo.conf (5)
file.

.SH OPTIONS
.TP
.B \-a
use the 
.I averages
table to compute the graphs. This requires that 
.BR meteoavg (1)
is run either as a daemon or before
.BR meteograph (1)
to ensure all necessary averages are present in the
.I averages
table.
.TP
.BI \-c imagedir
write image files to 
.IR imagedir .
Note that 
.BR meteograph (1)
performs a
.BR chdir (2)
before opening the configuration file (as specified with the
.B \-f 
option below), so if a relative path for the configuration file
is used, it should be relativ to the image directory.
One possible application of this feature is to have a graph directory
for each weather station, and to put the meteo.conf
file in the same directory as the graphs. 
.BR meteograph (1) can then be called with

.nf
.ti +3
meteograph -c graphdir-a -f meteo.conf 7200
.ti +3
meteograph -c graphdir-b -f meteo.conf 7200
.fi

to reproduce all two hour graphs for stations
.I a
and
.IR b .
.TP
.B \-d
increase the debug level by one. Debug messages are written to standard
error.
.TP
.BI \-e endtime
compute graphs ending at
.IR endtime .
.TP
.BI \-f conffile
Use 
.I conffile
to read the configuration, see 
.BR meteo.conf (5)
for the configuration syntax. This argument is mandatory.
.TP
.BI \-g graphname
add a graph named
.I graphname
to the list of graphs to be produced. If this option is specified
once, no other graphs are produced than the ones specified.
.TP
.BI \-G graphname
suppress the graph named
.IR graphname ,
but otherwise produce all graphs.
If this option is used several times, all graphs specified are
suppressed.
.TP
.B \-t
include the timestamp in the file name of the generated image files.

.SH "SEE ALSO"
.BR meteo (1)
.BR meteo.conf (5),
.BR meteoloop (1),
.BR meteoavg (1),
.BR meteodequeue (1),
.BR meteocheck (1),
.BR meteojob (1)

.SH AUTHOR
Dr. Andreas Mueller <afm@othello.ch>
