.TH METEO.CONF "5" "December 2001" "Meteo station tools" Othello
.SH NAME
meteo.conf \- description of configuration file format
.SH DESCRIPTION
The meteo station tools are described in 
.BR meteo (1),
this manual page defines the configuration file format used by all
the utilities.
The syntax is similar to that of the configuration of 
.BR gated (8)
or BIND  version 8 or later.
It consists of statements terminated by a semicolon, grouped together
in sections by braces, preceded by the section name.
There are mandatory sections that describe the weather station
(named
.IR station )
and the database connection (named
.IR database ).
Further sections describe the graphs to be produced, and are only
used by the
.BR meteograph (1)
program. The names of these sections are the graph names defined
in the manual page of
.BR meteograph (1).
The contens of these sections are explained below.
Strings have to be enclosed in quotation marks.

.SH "STATION CONFIGURATION"
The station section defines the interface through which weather data
is to be read from the station. It contains the following options:
.TP
.BI url\  stationurl
can be a file URL
.IR file:///dev/ttyS0 ,
indicating that a serial device should be used to communicate with
the station.
A TCP url of the form
.I tcp://192.168.7.3:10001
can be used to communicate with the station over the network through
a terminal server or device server, the example works for a 
Lantronix UDS-10 devices server.
.TP
.BI speed\  baudrate
This item is only needed for serial communication, and specifies the
baud rate to use. Older Davis stations (Weather Monitor II) use
2400 baud, the Vantage Pro runs at 19200 baud.
.TP
.BI type\  stationtype
As weather station protocols vary substantially for the various types
of stations, and there don't seem to be reliably methods to find out
the type of station, the station type must be specified. Possible
values are (for historical reasons)
.I Davis
and
.IR Vantage .

The following
.I station
section sample is used with the Vantage Pro station in Bosco/Gurin:

.nf
.in +4
station {
.in +4
url "tcp://192.168.7.3:10001";
speed 19200;
type "Vantage";
.in -4
}
.in -4
.fi

.SH "DATABASE CONFIGURATION"
The
.I database
section defines the connection to the database, i.e. hostname,
database name and user names and passwords.
It also includes the prefix by which data from this station is identified
in the database. This prefix is also used for the graph names.
The section contains the following statements

.TP
.BI "hostname " dbserver
The host name on which the MySQL server runs.
.TP
.BI "dbname " databasename
The name of the database, usualy
.IR meteo .
.TP
.BI "prefix " stationname
The name of the weather station.
.TP
.BI "user " readonly-user
A user name for a user that is granted select access to the
.I stationdata 
and the
.I averages
tables. The
.BR meteograph (1)
program uses this identity to access the database.
.TP
.BI "password " readonly-password
The password for the read only user.
.TP
.BI "writer " readwrite-user
The name of a user granted select, update and insert on the
.I stationdata
and
.I averages
tables.  The 
.BR meteoloop (1)
and 
.BR meteoavg (1)
programs use this identity to update the database.
.TP
.BI "writerpassword " readwrite-password
The password of the read/write identity defined with the
.B writer
directive.
.TP
.BI "msgqueue " queuefile
System V message queues are identified by a 32bit message ID, but this
is very system dependent. The
.B msgqueue
directive specifies the name of a file, from which a message queue
id will be derived. There are no other requirements on the file name
than that it exists.

Here is the configuration of the station in Bosco/Gurin as a sample

.nf
.in +4
database {
.in +4
hostname "localhost";
dbname "meteo";
prefix "Gurin";
user "meteo";
password "public";
writer "meteoupdate";
writerpassword "secret";
msgqueue "/tmp/meteodb-queue";
.in -4
};
.in -4
.fi

.SH "GRAPH CONFIGURATION"
The graph sections define the colors for the various curves and histograms,
and the vertical scales and ranges.
Some graphs combine more than one data channel with different units in the
same graphs.
These graphs have two different scales, and are labeled differently on the
left and on the right.
To specify different data for the left and the right subgraph, the sections
named
.I left
and 
.I right
are used.

Some data, most notably rain, which is cumulative, need to use different
scales for the different time resolutions.
It is therefore possible to specify a section named 

.I interval { 300 | 1800 | 7200 | 86400 }

to define differing parameters for these sampling intervals.
These 
.I interval
sections must be contained within a 
.I left
or
.I right
section.
However, parameters specified inside a graph section, or inside a 
.I left
or 
.I right
section are inherited by the side section or the interval section,
and don't need to be specified again if the are identical.

The following parameters are common to all graphs:

.TP
.BI "color " "r g b"
Color of the main graph curve. Additional colors may be defined in some of
the graphs.
See the description of the individual graph names below for other graphs.
Colors are specified as RGB-Triples,
.I r g
and
.I b
are integers between 0 and 255 and indicate the red, green and blue part.
.TP
.BI "nodatacolor " "r g b"
Color the background for those those segments of the graph with this
color, if specified, otherwise the background color is used. This lets
stand out the time segments without data a bit better.
.TP
.BI "label " labelstring
A string to be displayed on the side of the graph, usually to describe
the kind of data displayed and the unit.
.TP
.BI "format " formatstring
C printf format string for the labeling of the tick marks on the
vertical axis of the graph. Usualy something like "%.1f".
.TP
.BI "min " value
Minimum value on the vertical axis.
.TP
.BI "max " value
Maximum value on the vertical axis.
.TP
.BI "scale " value
Defines how much a pixel is in the values of the vertical axis.
.TP
.BI "step " value
Distance between the tick marks.
.TP
.BI "start " value
First tick mark value.
.TP
.BI "end " value
Last tick mark value.

.SH "SPECIALITIES"
Below we describe how each graph interprets the main color and what
other color specifications are available.

.TP
.B temperature

The main color is used for the average temperature. Additional colors
are 
.B rangecolor
for the temperature range between minimum and maximum temperature within
the sampling interval and
.B dewcolor
for the dew point temperature computed from the relative humidity.

.TP
.B temperature_inside

Same as 
.B temperature
but for inside temperature and inside humidity.

.TP
.B barometer

The average barometric pressure is display in the main color, the
.B rangecolor
is used to display the range between minimum and maximum pressure.

.TP
.B wind

The wind graph contains a histogram of wind speed and maximum speed
(within the sampling interval), they are display in the colors
specified by the
.B speedcolor
and
.B gustcolor
directives. 
The main color is used for the wind azimut. The azimut ist
displayed based on the scale on the right side of the graph, so a
.B right
directive is required. On the Bosco/Gurin weather station, the following
.B right
section is used:

.nf
.in +4
right {
.in +4
label "            Azimut (deg)";
format "%.0f";
min -604;
max 360;
scale 8;
start 0;
end 360;
step 180;
.in -4
};
.in -4
.fi


.TP
.B rain

The rain graph contains only the histogram of total rain drawn in
the main color. But as rain is cumulative, the various intervals
use different scales. The Bosco/Gurin weather station uses the following
settings

.nf
.in +4
rain {
.in +4
color 0 0 255;
min 0;
start 0;
left {
.in +4
label "Precipitation (mm)";
format "%.0f";
interval 300 {
.in +4
format "%.1f";
scale 0.008333333;
step .5;
.in -4
};
interval 1800 {
.in +4
scale 0.05;
step 1;
.in -4
};
interval 7200 {
.in +4
scale .08333333;
step 5;
.in -4
};
interval 86400 {
.in +4
scale .25;
step 10;
.in -4
};
.in -4
};
.in -4
};
.in -4
.fi

Note how the values of
.I min
and
.I start
as well as the
.I label
and
.I format
strings are inherited by the 
.I interval
directives.

.TP
.B radiation

The radiation graph combines a histogram of total solar radiation
(in W/m^2) drawn in the main color with a curve of the UV index
drawn in the
.BR uvcolor .
This graph also uses two different scales on both sides of the
graph.

.SH "SEE ALSO"
.BR meteo (1),
.BR meteoloop (1),
.BR meteoavg (1),
.BR meteograph (1),
.BR meteodequeue (1),
.BR meteocheck (1),
.BR meteojob (1)

.SH AUTHOR
Dr. Andreas Mueller <afm@othello.ch>
