.TH METEOSENSORS "1" "July 2003" "Meteo station tools" Othello
.SH NAME
meteosensors \- display the sensor names a station understands
.SH SYNOPSIS
meteosensors stationtype
.SH DESCRIPTION
The 
.BR meteosensors (1)
programm displays a list of sensor names, value classes and station units
for a particular station type. Exactly these names can be used in the
.BR meteo.xml (5)
configuration file. Note that there is now way for the software to find
out whether the sensor you specify is actually connected to the station.
In particular, the VantagePro station cannot have all the sensors
simultaneously.

The error message printed when
.BR meteosenors (1)
is called with unknown or no arguments includes a list of all station
types known to meteo.

.SH "SEE ALSO"
.BR meteo (1),
.BR meteo.xml (5)

.SH AUTHOR
Dr. Andreas Mueller <afm@othello.ch>
