#! /sbin/sh
#
# (c) 2001 Dr. Andreas Mueller, Beratung und Entwicklung
#
# Note: this script assumes the average table has correctly been filled
#       e.g. using the meteoavg program
#
# $Id: meteojob,v 1.4 2003/06/13 00:55:29 afm Exp $
#
station=Altendorf
s=`/usr/local/bin/date +%s`
s=`expr $s - \( $s % 300 \)`

for interval in 300 1800 7200 86400
do
	if [ `expr $s % $interval` -eq 0 ]
	then
		/usr/local/bin/meteograph -s ${station} -a "$@" ${interval}
	fi
done

exit 0
